apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-root-password: cm9vdHBhc3M=         # "rootpass" בבייס64
  mysql-user: Zmxhc2thcHA=                 # "flaskapp" בבייס64
  mysql-password: Zmxhc2thcHA=             # "flaskapp" בבייס64
  mysql-database: ZXhhbXBsZURi             # "exampleDb" בבייס64
