version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword123
      MYSQL_DATABASE: exampleDb
      MYSQL_USER: flaskapp
      MYSQL_PASSWORD: flaskapp
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - workprofile-network

  workprofile:
    build: ./backend
    container_name: workprofile-app
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: mysql
      DB_USER: flaskapp
      DB_PASS: flaskapp
      DB_NAME: exampleDb
    networks:
      - workprofile-network

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./static:/usr/share/nginx/html/static
    depends_on:
      - workprofile
    networks:
      - workprofile-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: rootpassword123
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - workprofile-network

networks:
  workprofile-network:
    driver: bridge

volumes:
  mysql-data:
